# Generated by Django 5.1.1 on 2024-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_model",
            name="user_id",
        ),
        migrations.AddField(
            model_name="user_model",
            name="user_password",
            field=models.CharField(default="", max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user_model",
            name="user_email",
            field=models.CharField(default="", max_length=128, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="user_model",
            name="user_name",
            field=models.CharField(default="", max_length=128, verbose_name="name"),
        ),
    ]
